import { Router } from "express";
import { asyncHandler } from "../utils/async-handler.js";
import { healthController } from "../controllers/health.controller.js";
import { authRouter } from "../modules/auth/auth.routes.js";
import { usersRouter } from "../modules/users/users.routes.js";
import { businessRouter } from "../modules/business/business.routes.js";
import { rolesRouter } from "../modules/roles/roles.routes.js";
import { permissionsRouter } from "../modules/permissions/permissions.routes.js";
import { dashboardRouter } from "../modules/dashboard/dashboard.routes.js";
import { fleetRouter } from "../modules/fleet/fleet.routes.js";
import { driversRouter } from "../modules/drivers/drivers.routes.js";
import { shipmentsRouter } from "../modules/shipments/shipments.routes.js";
import { deliveriesRouter } from "../modules/deliveries/deliveries.routes.js";
import { customersRouter } from "../modules/customers/customers.routes.js";
import { suppliersRouter } from "../modules/suppliers/suppliers.routes.js";
import { maintenanceRouter } from "../modules/maintenance/maintenance.routes.js";
import { billingRouter } from "../modules/billing/billing.routes.js";
import { paymentsRouter } from "../modules/payments/payments.routes.js";
import { reportsRouter } from "../modules/reports/reports.routes.js";
import { notificationsRouter } from "../modules/notifications/notifications.routes.js";
import { uploadsRouter } from "./uploads.routes.js";

export const apiRouter = Router();

apiRouter.get("/health", asyncHandler(healthController.check));
apiRouter.use("/auth", authRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use("/business", businessRouter);
apiRouter.use("/roles", rolesRouter);
apiRouter.use("/permissions", permissionsRouter);
apiRouter.use("/dashboard", dashboardRouter);
apiRouter.use("/fleet", fleetRouter);
apiRouter.use("/drivers", driversRouter);
apiRouter.use("/shipments", shipmentsRouter);
apiRouter.use("/deliveries", deliveriesRouter);
apiRouter.use("/customers", customersRouter);
apiRouter.use("/suppliers", suppliersRouter);
apiRouter.use("/maintenance", maintenanceRouter);
apiRouter.use("/billing", billingRouter);
apiRouter.use("/payments", paymentsRouter);
apiRouter.use("/reports", reportsRouter);
apiRouter.use("/notifications", notificationsRouter);
apiRouter.use("/uploads", uploadsRouter);
