/**
 * Customer portal URL helpers for admin credential sharing.
 * Uses VITE_CUSTOMER_PORTAL_URL only — never hardcode production hosts in callers.
 */

function trimSlash(url) {
  return String(url || "").trim().replace(/\/+$/, "");
}

export function getCustomerPortalBaseUrl() {
  const fromEnv = trimSlash(import.meta.env.VITE_CUSTOMER_PORTAL_URL);
  if (fromEnv) return fromEnv;
  // Safe defaults when env is missing (dev vs prod build).
  return import.meta.env.PROD ? "https://portal.logisticflow.app" : "http://localhost:5173";
}

export function buildCustomerPortalLoginUrl(businessId) {
  const code = String(businessId || "").trim().toUpperCase();
  if (!code) return getCustomerPortalBaseUrl();
  return `${getCustomerPortalBaseUrl()}/login/${code}`;
}

/** Normalize API credentials so Portal URL always comes from frontend env. */
export function normalizePortalCredentials(credentials = {}, extras = {}) {
  const businessId = credentials.businessId || extras.businessId || "";
  return {
    customerName: credentials.customerName || extras.customerName || "",
    customerId: credentials.customerId || extras.customerId || "",
    temporaryPassword: credentials.temporaryPassword || "",
    businessId,
    companyName: credentials.companyName || extras.companyName || "",
    loginUrl: buildCustomerPortalLoginUrl(businessId),
  };
}

export function buildPortalLoginDetailsText(credentials) {
  const c = normalizePortalCredentials(credentials);
  return [
    "Customer Portal Login",
    "",
    "Business:",
    c.companyName || "—",
    "",
    "Business ID:",
    c.businessId || "—",
    "",
    "Customer:",
    c.customerName || "—",
    "",
    "Customer ID:",
    c.customerId || "—",
    "",
    "Temporary Password:",
    c.temporaryPassword || "—",
    "",
    "Portal:",
    c.loginUrl,
    "",
    "Please change your password after first login.",
  ].join("\n");
}

export function buildPortalWhatsAppMessage(credentials) {
  const c = normalizePortalCredentials(credentials);
  return [
    `Hello ${c.customerName || "Customer"},`,
    "",
    "Your customer portal has been created.",
    "",
    "Business:",
    c.companyName || "—",
    "",
    "Customer ID:",
    c.customerId || "—",
    "",
    "Temporary Password:",
    c.temporaryPassword || "—",
    "",
    "Portal:",
    c.loginUrl,
    "",
    "Please change your password after your first login.",
    "",
    "Thank you.",
  ].join("\n");
}

export function buildPortalEmailHtml(credentials) {
  const c = normalizePortalCredentials(credentials);
  const row = (label, value) =>
    `<tr><td style="padding:6px 0;color:#64748b;font-size:13px;width:140px;">${label}</td><td style="padding:6px 0;color:#0f172a;font-size:14px;font-weight:600;">${value || "—"}</td></tr>`;

  return `<!DOCTYPE html>
<html>
<body style="margin:0;padding:24px;background:#f8fafc;font-family:Helvetica,Arial,sans-serif;">
  <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden;">
    <tr>
      <td style="padding:20px 24px;background:#2f5bff;color:#ffffff;font-size:18px;font-weight:700;">Customer Portal Login</td>
    </tr>
    <tr>
      <td style="padding:24px;">
        <p style="margin:0 0 16px;color:#334155;font-size:14px;line-height:1.5;">Hello ${c.customerName || "Customer"},</p>
        <p style="margin:0 0 20px;color:#334155;font-size:14px;line-height:1.5;">Your customer portal has been created. Please change your password after your first login.</p>
        <table role="presentation" width="100%" cellspacing="0" cellpadding="0">
          ${row("Business", c.companyName)}
          ${row("Business ID", c.businessId)}
          ${row("Customer", c.customerName)}
          ${row("Customer ID", c.customerId)}
          ${row("Temporary Password", c.temporaryPassword)}
          ${row("Portal", `<a href="${c.loginUrl}" style="color:#2f5bff;text-decoration:none;">${c.loginUrl}</a>`)}
        </table>
        <p style="margin:24px 0 0;color:#94a3b8;font-size:12px;">Generated by LogisticsFlow</p>
      </td>
    </tr>
  </table>
</body>
</html>`;
}

export function buildPortalEmailMailto(credentials) {
  const c = normalizePortalCredentials(credentials);
  const subject = `Customer Portal Login — ${c.companyName || "LogisticsFlow"}`;
  const body = buildPortalWhatsAppMessage(c);
  return {
    subject,
    body,
    href: `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`,
    html: buildPortalEmailHtml(c),
  };
}
